Upgrade to build system 2.4.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -435,6 +435,10 @@ if [[ -z "${NTF_CONFIGURE_FROM_PACKAGING}" ]]; then
     NTF_CONFIGURE_FROM_PACKAGING=0
 fi
 
+if [[ -z "${NTF_CONFIGURE_VERBOSITY}" ]]; then
+    NTF_CONFIGURE_VERBOSITY=0
+fi
+
 NTF_CONFIGURE_VERBOSE=0
 NTF_CONFIGURE_WHAT=0
 NTF_CONFIGURE_CLEAN=1
@@ -833,6 +837,8 @@ while true ; do
 
         --verbose)
             NTF_CONFIGURE_VERBOSE=1 ; shift ;;
+        --verbosity)
+            NTF_CONFIGURE_VERBOSITY=$2 ; shift 2 ;;
         --what)
             NTF_CONFIGURE_WHAT=1 ; shift ;;
         --clion_config)
@@ -934,6 +940,8 @@ export NTF_CONFIGURE_WITH_DOCUMENTATION_INTERNAL
 export NTF_CONFIGURE_FROM_CONTINUOUS_INTEGRATION
 export NTF_CONFIGURE_FROM_PACKAGING
 
+export NTF_CONFIGURE_VERBOSITY
+
 cd ${NTF_CONFIGURE_REPOSITORY}
 
 if [ ${NTF_CONFIGURE_CLEAN} -eq 1 ]; then
@@ -1019,6 +1027,29 @@ else
 NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE=" -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF"
 fi
 
+if [ ${NTF_CONFIGURE_VERBOSITY} -eq 0 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="UNDEFINED"
+elif [ ${NTF_CONFIGURE_VERBOSITY} -eq 1 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="ERROR"
+elif [ ${NTF_CONFIGURE_VERBOSITY} -eq 2 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="WARNING"
+elif [ ${NTF_CONFIGURE_VERBOSITY} -eq 3 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="STATUS"
+elif [ ${NTF_CONFIGURE_VERBOSITY} -eq 4 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="DEBUG"
+elif [ ${NTF_CONFIGURE_VERBOSITY} -eq 5 ]; then
+    NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL="TRACE"
+else
+    echo "Invalid verbosity: ${NTF_CONFIGURE_VERBOSITY}"
+    exit 1
+fi
+
+if [ ${NTF_CONFIGURE_VERBOSITY} -eq 0 ]; then
+NTF_CONFIGURE_CMAKE_OPTION_VERBOSITY=""
+else
+NTF_CONFIGURE_CMAKE_OPTION_VERBOSITY=" --log-level=TRACE -DCMAKE_MESSAGE_LOG_LEVEL:STRING=${NTF_CONFIGURE_CMAKE_OPTION_LOG_LEVEL} -DCMAKE_MESSAGE_CONTEXT_SHOW:BOOL=ON"
+fi
+
 if ${NTF_CONFIGURE_MAKE} -v 2>&1 | grep "GNU Make" >/dev/null 2>&1; then
 NTF_CONFIGURE_MAKEFLAGS="--no-print-directory"
 fi
@@ -1051,8 +1082,8 @@ fi
 
 cd ${NTF_CONFIGURE_OUTPUT}
 
-echo "${NTF_CONFIGURE_CMAKE}${NTF_CONFIGURE_CMAKE_OPTION_DISTRIBUTION_REFROOT}${NTF_CONFIGURE_CMAKE_OPTION_UFID}${NTF_CONFIGURE_CMAKE_OPTION_BUILD_TYPE}${NTF_CONFIGURE_CMAKE_OPTION_INSTALL_PREFIX}${NTF_CONFIGURE_CMAKE_OPTION_PREFIX_PATH}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE} -DCMAKE_TOOLCHAIN_FILE:PATH=${NTF_CONFIGURE_TOOLCHAIN} -G \"${NTF_CONFIGURE_GENERATOR}\" -S ${NTF_CONFIGURE_REPOSITORY}"
-${NTF_CONFIGURE_CMAKE}${NTF_CONFIGURE_CMAKE_OPTION_DISTRIBUTION_REFROOT}${NTF_CONFIGURE_CMAKE_OPTION_UFID}${NTF_CONFIGURE_CMAKE_OPTION_BUILD_TYPE}${NTF_CONFIGURE_CMAKE_OPTION_INSTALL_PREFIX}${NTF_CONFIGURE_CMAKE_OPTION_PREFIX_PATH}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE} -DCMAKE_TOOLCHAIN_FILE:PATH=${NTF_CONFIGURE_TOOLCHAIN} -G "${NTF_CONFIGURE_GENERATOR}" -S ${NTF_CONFIGURE_REPOSITORY}
+echo "${NTF_CONFIGURE_CMAKE}${NTF_CONFIGURE_CMAKE_OPTION_DISTRIBUTION_REFROOT}${NTF_CONFIGURE_CMAKE_OPTION_UFID}${NTF_CONFIGURE_CMAKE_OPTION_BUILD_TYPE}${NTF_CONFIGURE_CMAKE_OPTION_INSTALL_PREFIX}${NTF_CONFIGURE_CMAKE_OPTION_PREFIX_PATH}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSITY}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE} -DCMAKE_TOOLCHAIN_FILE:PATH=${NTF_CONFIGURE_TOOLCHAIN} -G \"${NTF_CONFIGURE_GENERATOR}\" -S ${NTF_CONFIGURE_REPOSITORY}"
+${NTF_CONFIGURE_CMAKE}${NTF_CONFIGURE_CMAKE_OPTION_DISTRIBUTION_REFROOT}${NTF_CONFIGURE_CMAKE_OPTION_UFID}${NTF_CONFIGURE_CMAKE_OPTION_BUILD_TYPE}${NTF_CONFIGURE_CMAKE_OPTION_INSTALL_PREFIX}${NTF_CONFIGURE_CMAKE_OPTION_PREFIX_PATH}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSITY}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE} -DCMAKE_TOOLCHAIN_FILE:PATH=${NTF_CONFIGURE_TOOLCHAIN} -G "${NTF_CONFIGURE_GENERATOR}" -S ${NTF_CONFIGURE_REPOSITORY}
 
 if [ ${?} -ne 0 ]; then
     echo "Failed to configure"
