generate cmake.xml - add new configuration in addition to existing

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15,30 +15,8 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-process_env() {
-  if [ -n "${!1}" ]; then
-    echo "            <env name=\"${1}\" value=\"${!1}\" />" >> "${NTF_CLION_XML}"
-  fi
-}
-
-generate_clion_toolchain () {
-  NTF_CLION_STORAGE="testFolder"
-  NTF_CLION_XML="${NTF_CLION_STORAGE}/cmake.xml"
-
-  mkdir -p ${NTF_CLION_STORAGE}
-
-  if test -f "$NTF_CLION_XML"; then
-    echo "cmake.xml exists, it will be overwritten"
-  fi
-
-  num_threads=$(grep ^processor /proc/cpuinfo | uniq | wc -l)
-
+write_config_header() {
   {
-    echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
-    echo "<project version=\"4\">"
-    echo "  <component name=\"CMakeSharedSettings\">"
-    echo "    <configurations>"
-
     echo -n "      <configuration PROFILE_NAME=\"${NTF_CONFIGURE_UFID_CANONICAL}\" ENABLED=\"true\""
     echo -n " GENERATION_DIR=\"${NTF_CONFIGURE_OUTPUT}\" CONFIG_NAME=\"${NTF_CONFIGURE_UFID_CANONICAL}\""
     echo -n " GENERATION_OPTIONS=\""
@@ -54,7 +32,59 @@ generate_clion_toolchain () {
 
     echo "        <ADDITIONAL_GENERATION_ENVIRONMENT>"
     echo "          <envs>"
-  } > ${NTF_CLION_XML}
+  } >> "${NTF_CLION_XML}"
+}
+
+process_env() {
+  if [ -n "${!1}" ]; then
+    echo "            <env name=\"${1}\" value=\"${!1}\" />" >> "${NTF_CLION_XML}"
+  fi
+}
+
+generate_clion_toolchain () {
+  echo "Generating Clion cmake.xml..."
+
+  NTF_CLION_STORAGE="testFolder"
+  NTF_CLION_XML="${NTF_CLION_STORAGE}/cmake.xml"
+
+  CLION_XML_GENERATION=$1
+  echo "CLION_XML_GENERATION = ${CLION_XML_GENERATION}"
+
+  mkdir -p ${NTF_CLION_STORAGE}
+
+  num_threads=$(grep ^processor /proc/cpuinfo | uniq | wc -l)
+
+  if [[ ${CLION_XML_GENERATION} == "clean" ]]; then
+    if test -f "$NTF_CLION_XML"; then
+      echo "cmake.xml exists, it will be overwritten"
+    fi
+
+    {
+      echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
+      echo "<project version=\"4\">"
+      echo "  <component name=\"CMakeSharedSettings\">"
+      echo "    <configurations>"
+    } > ${NTF_CLION_XML}
+
+    write_config_header
+
+  elif [[ ${CLION_XML_GENERATION} == "add" ]]; then
+    echo "Additional generation"
+
+    if ! test -f "${NTF_CLION_XML}"; then
+      echo "cmake.xml does not exist, aborting"
+      exit -1
+    fi
+
+    #save previously available configurations, remove only the end of the cmake.xml
+    num_lines=$(grep -n '</configurations>' ${NTF_CLION_XML} | awk '{print $1}')
+    num_lines=${num_lines:0:${#num_lines}-1}
+    num_lines=$(($((num_lines))-1))
+    head -"${num_lines}" ${NTF_CLION_XML} > clion_tmpfile && mv clion_tmpfile ${NTF_CLION_XML}
+
+    write_config_header
+
+  fi
 
   process_env "CC"
   process_env "CXX"
@@ -130,7 +160,12 @@ generate_clion_toolchain () {
     echo "  </component>"
     echo "</project>"
   } >> ${NTF_CLION_XML}
+
+  echo "Generating Clion cmake.xml done"
 }
+
+
+
 
 set -o pipefail
 
@@ -404,7 +439,7 @@ fi
 NTF_CONFIGURE_VERBOSE=0
 NTF_CONFIGURE_WHAT=0
 NTF_CONFIGURE_CLEAN=1
-NTF_GENERATE_CLION_CONFIG=0
+#NTF_GENERATE_CLION_CONFIG="NO"
 
 usage()
 {
@@ -745,7 +780,7 @@ while true ; do
         --what)
             NTF_CONFIGURE_WHAT=1 ; shift ;;
         --clion)
-            NTF_GENERATE_CLION_CONFIG=1 ; shift ;;
+            NTF_GENERATE_CLION_CONFIG=$2 ; shift 2 ;;
         --*)
             echo "Invalid option: ${1}"
             usage ;;
@@ -935,14 +970,13 @@ fi
 
 NTF_CONFIGURE_CMAKE_OPTION_UFID=" -DUFID:STRING=${NTF_CONFIGURE_UFID_CANONICAL}"
 
-if [ ${NTF_GENERATE_CLION_CONFIG} -ne 0 ]; then
-  generate_clion_toolchain
+if [ -n "${NTF_GENERATE_CLION_CONFIG}" ]; then
+  generate_clion_toolchain "${NTF_GENERATE_CLION_CONFIG}"
   exit 0
 fi
 
 
 cd ${NTF_CONFIGURE_OUTPUT}
-
 
 echo "${NTF_CONFIGURE_CMAKE}${NTF_CONFIGURE_CMAKE_OPTION_DISTRIBUTION_REFROOT}${NTF_CONFIGURE_CMAKE_OPTION_UFID}${NTF_CONFIGURE_CMAKE_OPTION_BUILD_TYPE}${NTF_CONFIGURE_CMAKE_OPTION_INSTALL_PREFIX}${NTF_CONFIGURE_CMAKE_OPTION_PREFIX_PATH}${NTF_CONFIGURE_CMAKE_OPTION_VERBOSE_MAKEFILE} -DCMAKE_TOOLCHAIN_FILE:PATH=${NTF_CONFIGURE_REPOSITORY}/toolchain.cmake -G \"${NTF_CONFIGURE_GENERATOR}\" -S ${NTF_CONFIGURE_REPOSITORY}"
 
